### ISSUE TITLE
cargo add package: please, not reformat Cargo.toml

### ISSUE THREAD

**Issue by Dushistov** [withoutboats/cargo-add#7]
For example:

```sh
cargo new --bin foo
cd foo
git add *
git commit -a -m "initial commit"
cargo add lazy_static
git diff
```

```diff
ndex f01daa4..c73c5f9 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -1,6 +1,7 @@
 [package]
+authors = ["Evgeniy A. Dushistov <email>"]
 name = "foo"
 version = "0.1.0"
-authors = ["Evgeniy A. Dushistov <email>"]
 
 [dependencies]
+lazy_static = "0.2.8"
```

as you see it not only add one dependency,
but also move "author line",
also if I have lines in form of:

```toml
[dependencies]
x = {git = "url", rev = "..." }
```
it reformat it to 
```toml
[dependencies.x]
git = ""
rev = ""
```

yes, it is equavalent, but why it touchs lines that not related to it's job,
and reduce noise in `git diff` output
